### ISSUE TITLE
Error registering

### ISSUE THREAD

**Issue by erdembekci** [mybbgroup/iPatrol#21] opened 2019-10-25 06:51 UTC
I get an error like this. gives error code 500 when trying to register

Error_Log
#0 /home/h49802a0/public_html/member.php(95): pluginSystem->run_hooks(Array)
#1 {main}

**Comment by effone** [comment] 2019-10-27 17:29
Can you please provide more details like it happened with which gateway, what kind of account etc it will help reproducing the issue and further debugging please...

**Comment by Eldenroot** [comment] 2020-01-03 20:45
#22 same here on my forum :(

**Comment by effone** [comment] 2020-06-12 18:57
This has already been fixed by @Eldenroot vide his PR #20 
https://github.com/mybbgroup/iPatrol/pull/20/files

Please use the latest repo version or just make sure this line is commented out / removed at line 290
`$plugins->add_hook('member_do_register_start', 'ipatrol_ban_regdupe');`

**Closed as completed by effone** 2020-06-12 18:57 UTC
